# fly.toml app configuration file generated for backendchater on 2025-10-04T13:37:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backendchater'
<<<<<<< HEAD
primary_region = 'ams'
=======
primary_region = 'fra'
>>>>>>> 05c313082474099fd73f1d4e1f7846c8b15fdd7d

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
